mysql:
  charset: utf8mb4
  db: go-mega
  host: localhost
  port: 3306
  password: root
  user: root
session:
  name: gomega
  authKey: qwertyuiop
  encryptKey: $@2XWjh4teFLIC31KfUMaaS*Roqeis^k
  maxAge: 10800
  httpOnly: true
basic:
  pageLimit: 5
mail:
  smtp:smtp.163.com
  smtp-port: 587
  username: isfogg@163.com
  password: